### ISSUE TITLE
Bug: It is not compiling on Xcode Version 7.0.1 (7A1001) and iOS 9 from a pod install or even from sample run

### ISSUE THREAD

**Issue by stremblayiOS** [gmertk/BusyNavigationBar#6]
<img width="886" alt="screen shot 2015-10-07 at 1 05 25 pm" src="https://cloud.githubusercontent.com/assets/919665/10344935/1d5f7732-6cf4-11e5-9910-e713c9a83237.png">

**Comment by gmertk** [comment]
Hi @stremblayiOS I didn't have time to update this for Swift 2. This one should be related to http://stackoverflow.com/questions/30872626/swift-2-0-replicate-objc-association-retain

Feel free to send a pull request!

**Comment by gmertk** [comment]
Updated now thanks to @lumenlunae
